# Generated by Django 2.2.14 on 2020-08-17 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='url',
            field=models.CharField(default='#', max_length=200),
        ),
    ]
